
const KEY='financial-manager-pro-v1';
const LEGACY='my_finance_manager_v1';
const DEFAULT_CATS=['مواد غذایی','قبض و اینترنت','حمل‌ونقل','خرید','حقوق','تعمیرات','قطعات موبایل','اجاره','فروش','خدمات','سرمایه‌گذاری','قسط بانکی','سایر'];
const BANKS=['بانک ملی ایران','بانک ملت','بانک تجارت','بانک صادرات ایران','بانک سپه','بانک رفاه کارگران','بانک مسکن','بانک کشاورزی','بانک توسعه صادرات ایران','بانک توسعه تعاون','پست بانک ایران','بانک صنعت و معدن','بانک کارآفرین','بانک پارسیان','بانک سامان','بانک پاسارگاد','بانک اقتصاد نوین','بانک سینا','بانک شهر','بانک دی','بانک آینده','بانک ایران زمین','بانک گردشگری','بانک خاورمیانه','بانک قرض‌الحسنه مهر ایران','بانک قرض‌الحسنه رسالت','بانک حکمت ایرانیان','بانک انصار','بانک سرمایه','بانک ایران‌زمین','سایر'];
const $=id=>document.getElementById(id);
let privacy=false, currentAccount='personal', reportMode='month', fabOpen=false;
const today=()=>new Date().toISOString().slice(0,10);
const JMONTHS=['فروردین','اردیبهشت','خرداد','تیر','مرداد','شهریور','مهر','آبان','آذر','دی','بهمن','اسفند'];
const JWEEK=['ش','ی','د','س','چ','پ','ج'];
function pad2(n){return String(n).padStart(2,'0')}
function g2j(gy,gm,gd){let g_d_m=[0,31,59,90,120,151,181,212,243,273,304,334];let gy2=gm>2?gy+1:gy;let days=355666+365*gy+Math.floor((gy2+3)/4)-Math.floor((gy2+99)/100)+Math.floor((gy2+399)/400)+gd+g_d_m[gm-1];let jy=-1595+33*Math.floor(days/12053);days%=12053;jy+=4*Math.floor(days/1461);days%=1461;if(days>365){jy+=Math.floor((days-1)/365);days=(days-1)%365}let jm=days<186?1+Math.floor(days/31):7+Math.floor((days-186)/30);let jd=1+(days<186?days%31:(days-186)%30);return [jy,jm,jd]}
function j2g(jy,jm,jd){jy+=1595;let days=-355668+365*jy+Math.floor(jy/33)*8+Math.floor((jy%33+3)/4)+jd+(jm<7?(jm-1)*31:(jm-7)*30+186);let gy=400*Math.floor(days/146097);days%=146097;if(days>36524){gy+=100*Math.floor(--days/36524);days%=36524;if(days>=365)days++}gy+=4*Math.floor(days/1461);days%=1461;if(days>365){gy+=Math.floor((days-1)/365);days=(days-1)%365}let gd=days+1,gm=0,monthDays=[31,(gy%4===0&&gy%100!==0)||gy%400===0?29:28,31,30,31,30,31,31,30,31,30,31];for(let i=0;i<12;i++){if(gd>monthDays[i]){gd-=monthDays[i]}else{gm=i+1;break}}return [gy,gm,gd]}
function isoToJalali(iso){if(!iso)return '';let [gy,gm,gd]=String(iso).slice(0,10).split('-').map(Number),j=g2j(gy,gm,gd);return `${fa(j[0])}/${fa(pad2(j[1]))}/${fa(pad2(j[2]))}`}
function jalaliToIso(value){let v=String(value||'').replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/[-.]/g,'/').trim();let m=v.match(/^(\d{4})\/(\d{1,2})\/(\d{1,2})$/);if(!m)return '';let [gy,gm,gd]=j2g(+m[1],+m[2],+m[3]);return `${gy}-${pad2(gm)}-${pad2(gd)}`}
function readJalali(id){let el=$(id);if(!el)return '';let iso=jalaliToIso(el.value);if(!iso){el.focus();throw new Error('تاریخ شمسی نامعتبر است');}return iso}
function dateField(id,iso){return `<div class="datefield"><input id="${id}" type="text" inputmode="numeric" autocomplete="off" placeholder="۱۴۰۵/۰۷/۱۴" value="${isoToJalali(iso||today())}" onblur="syncJalali('${id}')" oninput="syncJalali('${id}')"><button type="button" onclick="openJalaliPicker('${id}')">📅</button></div>`}
function syncJalali(id){let e=$(id);if(e) e.classList.toggle('invalid',!!e.value&&!jalaliToIso(e.value))}
let pickerState={id:'',y:0,m:0};
function openJalaliPicker(id){let e=$(id),iso=jalaliToIso(e.value)||today(),j=g2j(...iso.split('-').map(Number));pickerState={id:id,y:j[0],m:j[1]};renderJalaliPicker(j[0],j[1]);}
function renderJalaliPicker(y,m){let p=document.getElementById('jpicker');if(!p){p=document.createElement('div');p.id='jpicker';p.className='jpicker';document.body.appendChild(p)}pickerState.y=y;pickerState.m=m;let days=m<=6?31:(m<=11?30:((y%4===3)?30:29));let first=j2g(y,m,1),dow=(new Date(first[0],first[1]-1,first[2]).getDay()+1)%7;let html=`<div class="jpicker-head"><button type="button" onclick="moveJMonth(-1)">‹</button><div class="jpicker-title">${fa(y)} ${JMONTHS[m-1]}</div><button type="button" onclick="moveJMonth(1)">›</button></div><div class="jpicker-week">${JWEEK.map(x=>`<span>${x}</span>`).join('')}</div><div class="jpicker-days">`;for(let i=0;i<dow;i++)html+='<button type="button" class="jday empty"></button>';for(let d=1;d<=days;d++)html+=`<button type="button" class="jday" onclick="pickJDay(${y},${m},${d})">${fa(d)}</button>`;html+='</div>';p.innerHTML=html;let e=$(pickerState.id),r=e.getBoundingClientRect();p.style.top=Math.min(window.innerHeight-350,Math.max(10,r.bottom+6))+'px';p.style.left=Math.min(window.innerWidth-p.offsetWidth-10,Math.max(10,r.left))+'px'}
function moveJMonth(delta){let y=pickerState.y,m=pickerState.m+delta;if(m<1){m=12;y--}if(m>12){m=1;y++}renderJalaliPicker(y,m)}
function pickJDay(y,m,d){let [gy,gm,gd]=j2g(y,m,d);let iso=`${gy}-${pad2(gm)}-${pad2(gd)}`;let e=$(pickerState.id);e.value=`${fa(y)}/${fa(pad2(m))}/${fa(pad2(d))}`;e.classList.remove('invalid');e.dataset.iso=iso;document.getElementById('jpicker')?.remove()}
document.addEventListener('click',e=>{let p=document.getElementById('jpicker');if(p&&!p.contains(e.target)&&!e.target.closest('.datefield'))p.remove()});
const num=v=>Number(String(v??0).replace(/,/g,'').replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)))||0;
const fa=n=>Number(n||0).toLocaleString('fa-IR');
const money=n=>privacy?'••••••':fa(n)+' تومان';
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function load(){
 let raw=localStorage.getItem(KEY);
 if(raw){try{return JSON.parse(raw)}catch{}}
 let base={version:1,settings:{personalName:'حساب شخصی',shopName:'حساب مغازه تعمیرات موبایل',dark:false,pin:'',ratesApiKey:''},accounts:{personal:{transactions:[],debts:[],savings:[],goals:[],budgets:[],loans:[]},shop:{transactions:[],debts:[],savings:[],goals:[],budgets:[],loans:[]}}};
 let legacy=localStorage.getItem(LEGACY);
 if(legacy)try{
  let l=JSON.parse(legacy), a=base.accounts.personal;
  (l.finance||[]).forEach(x=>a.transactions.push({id:x.id||uid(),type:x.type==='income'?'income':'expense',amount:num(x.amount),date:x.date||today(),note:x.note||'',category:'سایر'}));
  (l.savings||[]).forEach(x=>a.savings.push({id:x.id||uid(),amount:num(x.amount),date:x.date||today(),note:x.note||'',goalId:''}));
  if(num(l.savingGoal))a.goals.push({id:uid(),name:'هدف قبلی',target:num(l.savingGoal),created:today()});
 }catch{}
 return base;
}
let data=load();
function normalizeData(){Object.values(data.accounts).forEach(a=>{a.transactions=a.transactions||[];a.debts=a.debts||[];a.savings=a.savings||[];a.goals=a.goals||[];a.budgets=a.budgets||[];a.loans=a.loans||[];a.loans.forEach(l=>{l.payments=l.payments||[];l.totalPayable=num(l.totalPayable||l.total||0);l.installment=num(l.installment||0);l.count=num(l.count||0);l.due=l.due||today();});});data.settings=data.settings||{personalName:'حساب شخصی',shopName:'حساب مغازه تعمیرات موبایل',dark:false,pin:'',ratesApiKey:''};data.settings.ratesApiKey=data.settings.ratesApiKey||'';}
normalizeData();
function save(){normalizeData();localStorage.setItem(KEY,JSON.stringify(data));renderAll()}
function active(){return data.accounts[currentAccount]}
function switchAccount(a){currentAccount=a;document.querySelectorAll('#accountBar button').forEach(b=>b.classList.toggle('active',b.dataset.account===a));renderAll();toast(a==='shop'?'حساب مغازه فعال شد':'حساب شخصی فعال شد')}
function monthKey(d){return (d||'').slice(0,7)}
function currentMonth(){return today().slice(0,7)}
function currentJMonth(){let j=g2j(...today().split('-').map(Number));return `${j[0]}-${pad2(j[1])}`}
function formatJMonth(m){if(!m)return '';let [y,mo]=m.split('-').map(Number);if(y>1500){let j=g2j(y,mo,1);y=j[0];mo=j[1]}return `${fa(y)} ${JMONTHS[mo-1]||''}`}
function monthName(){return new Date().toLocaleDateString('fa-IR',{month:'long',year:'numeric'})}
function formatDate(d){if(!d)return 'بدون تاریخ';try{return isoToJalali(d)}catch{return d}}
function jalaliParts(date){let d=date||new Date(),fmt=new Intl.DateTimeFormat('fa-IR-u-ca-persian',{year:'numeric',month:'2-digit',day:'2-digit'});return fmt.format(d)}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>$('toast').classList.remove('show'),1800)}
function totals(a=active(), month=null){
 let tx=a.transactions||[];if(month)tx=tx.filter(x=>monthKey(x.date)===month);
 let income=tx.filter(x=>x.type==='income').reduce((s,x)=>s+num(x.amount),0),expense=tx.filter(x=>x.type==='expense').reduce((s,x)=>s+num(x.amount),0);
 let saving=(a.savings||[]).reduce((s,x)=>s+num(x.amount),0);
 let debt=(a.debts||[]).reduce((s,x)=>s+Math.max(0,num(x.total)-num(x.paid)),0);
 return {income,expense,saving,balance:income-expense-saving,debt};
}
function renderAll(){renderDashboard();renderTransactions();renderDebts();renderLoans();renderSavings();renderBudgets();renderReports();$('monthName').textContent=monthName();$('accountName').textContent=currentAccount==='shop'?data.settings.shopName:data.settings.personalName;if(typeof refreshRates==='function')refreshRates(false)}
function renderDashboard(){
 let a=active(), t=totals(a), m=totals(a,currentMonth());
 $('spendable').textContent=money(t.balance);$('heroIncome').textContent=money(m.income);$('heroExpense').textContent=money(m.expense);$('heroSaving').textContent=money(t.saving);$('heroDebt').textContent=money(t.debt);$('heroLoanDebt').textContent=money((a.loans||[]).reduce((s,l)=>s+loanRemaining(l),0));
 $('totalIncome').textContent=money(t.income);$('totalExpense').textContent=money(t.expense);$('totalSaving').textContent=money(t.saving);$('totalDebt').textContent=money(t.debt);
 let goals=a.goals||[], gp=goals.length?goals.reduce((s,g)=>s+Math.min(100,(num(g.saved||0)/Math.max(1,num(g.target)))*100),0)/goals.length:0;$('goalProgress').textContent=fa(Math.round(gp))+'٪';
 let recent=[...(a.transactions||[])].sort((x,y)=>y.date.localeCompare(x.date)).slice(0,7);$('recentTransactions').innerHTML=recent.length?recent.map(txHTML).join(''):'<div class="empty">هنوز تراکنشی ثبت نشده است.</div>';
 let alerts=[];(a.debts||[]).filter(d=>remaining(d)>0&&d.due&&d.due<today()).forEach(d=>alerts.push(`<div class="alert red">⏰ بدهی مشتری <b>${esc(d.name)}</b> عقب افتاده است: ${money(remaining(d))}</div>`));
 (a.budgets||[]).filter(b=>b.month===currentMonth()).forEach(b=>{let used=spentCat(b.category,currentMonth());if(num(b.limit)>0&&used/num(b.limit)>=.8)alerts.push(`<div class="alert">⚠️ بودجه «${esc(b.category)}» ${fa(Math.round(used/num(b.limit)*100))}٪ مصرف شده است.</div>`)});
 (a.loans||[]).forEach(l=>{let r=loanRemaining(l),due=l.due;if(r>0&&due<today())alerts.push(`<div class="alert red">🏦 قسط بانکی «${esc(l.title||l.bank)}» عقب افتاده است.</div>`);else if(r>0&&due&&Math.ceil((new Date(due)-new Date(today()))/86400000)<=7)alerts.push(`<div class="alert">🏦 قسط «${esc(l.title||l.bank)}» نزدیک است: ${formatDate(due)}</div>`)});
 if(!alerts.length)alerts.push('<div class="alert green">✓ هشدار مهمی وجود ندارد.</div>');$('alerts').innerHTML=alerts.slice(0,6).join('');
 $('budgetMini').innerHTML=budgetHTML((a.budgets||[]).filter(b=>b.month===currentMonth()).slice(0,4));$('goalsMini').innerHTML=goalHTML(goals.slice(0,4));drawMainChart();
}
function txHTML(x){let c=x.type==='income'?'#16a34a':'#dc2626',sg=x.type==='income'?'+':'−';return `<div class="item"><div class="item-main"><span class="dot" style="background:${c}"></span><div><b>${x.type==='income'?'📈':'📉'} ${esc(x.note||x.category||'تراکنش')}</b><small>${formatDate(x.date)} • ${esc(x.category||'سایر')}</small></div></div><div style="text-align:left"><div class="money ${x.type==='income'?'success':'negative'}">${sg}${money(x.amount)}</div><button class="secondary" style="padding:4px 7px;font-size:9px;margin-top:4px" onclick="editTransaction('${x.id}')">ویرایش</button></div></div>`}
function openModal(title,body){$('modalTitle').textContent=title;$('modalBody').innerHTML=body;$('modal').classList.remove('hidden')}
function closeModal(){$('modal').classList.add('hidden')}
function openTransaction(type='expense',id=''){let x=active().transactions.find(t=>t.id===id);openModal(x?'ویرایش تراکنش':'تراکنش جدید',`<form class="form" onsubmit="saveTransaction(event,'${id}')"><div class="row"><div><label>نوع</label><select id="fType"><option value="income" ${(!x&&type==='income')||x?.type==='income'?'selected':''}>درآمد</option><option value="expense" ${(!x&&type==='expense')||x?.type==='expense'?'selected':''}>هزینه</option></select></div><div><label>مبلغ (تومان)</label><input id="fAmount" inputmode="numeric" required value="${x?.amount||''}"></div></div><div class="row"><div><label>تاریخ</label>${dateField("fDate",x?.date||today())}<small class="muted">تاریخ را به صورت شمسی وارد کنید.</small></div><div><label>دسته‌بندی</label><select id="fCat">${DEFAULT_CATS.map(c=>`<option ${x?.category===c?'selected':''}>${c}</option>`).join('')}</select></div></div><div><label>توضیحات</label><textarea id="fNote" placeholder="مثلاً فروش گوشی، خرید قطعه...">${esc(x?.note||'')}</textarea></div><div class="row"><button class="primary">ذخیره</button><button type="button" class="secondary" onclick="closeModal()">انصراف</button></div></form>`)}
function saveTransaction(e,id){e.preventDefault();let a=active(),old=a.transactions.find(x=>x.id===id),x={id:id||uid(),type:$('fType').value,amount:num($('fAmount').value),date:readJalali('fDate'),note:$('fNote').value.trim(),category:$('fCat').value};if(!x.amount)return;old?Object.assign(old,x):a.transactions.push(x);save();closeModal();toast('تراکنش ذخیره شد')}
function editTransaction(id){openTransaction('',id)}
function deleteTransaction(id){if(confirm('این تراکنش حذف شود؟')){active().transactions=active().transactions.filter(x=>x.id!==id);save();toast('حذف شد')}}
function renderTransactions(){let a=active(),q=($('txSearch')?.value||'').trim().toLowerCase(),type=$('txType')?.value||'',cat=$('txCategory')?.value||'',mo=$('txMonth')?.value||'';if($('txCategory'))$('txCategory').innerHTML='<option value="">همه دسته‌ها</option>'+[...new Set(a.transactions.map(x=>x.category).filter(Boolean))].map(c=>`<option ${cat===c?'selected':''}>${esc(c)}</option>`).join('');if($('txMonth'))$('txMonth').innerHTML='<option value="">همه ماه‌ها</option>'+[...new Set(a.transactions.map(x=>monthKey(x.date)).filter(Boolean))].sort().reverse().map(m=>`<option value="${m}" ${mo===m?'selected':''}>${m}</option>`).join('');let arr=[...a.transactions].filter(x=>(!q||(`${x.note} ${x.category}`).toLowerCase().includes(q))&&(!type||x.type===type)&&(!cat||x.category===cat)&&(!mo||monthKey(x.date)===mo)).sort((x,y)=>y.date.localeCompare(x.date));$('transactionsList').innerHTML=arr.length?`<div class="list">${arr.map(x=>`<div class="item">${txHTML(x).replace('</div></div>','')}</div>`).join('')}`:'<div class="empty">موردی پیدا نشد.</div>'}
function remaining(d){return Math.max(0,num(d.total)-num(d.paid))}
function openDebt(id=''){let x=active().debts.find(d=>d.id===id);openModal(x?'ویرایش بدهی':'ثبت بدهکار',`<form class="form" onsubmit="saveDebt(event,'${id}')"><div class="row"><div><label>نام مشتری</label><input id="dName" required value="${esc(x?.name||'')}"></div><div><label>شماره تماس</label><input id="dPhone" inputmode="tel" value="${esc(x?.phone||'')}"></div></div><div class="row"><div><label>مبلغ کل</label><input id="dTotal" inputmode="numeric" required value="${x?.total||''}"></div><div><label>پرداخت‌شده</label><input id="dPaid" inputmode="numeric" value="${x?.paid||0}"></div></div><div><label>تاریخ سررسید</label>${dateField("dDue",x?.due||today())}</div><div><label>توضیحات</label><textarea id="dNote">${esc(x?.note||'')}</textarea></div><button class="primary">ذخیره بدهی</button></form>`)}
function saveDebt(e,id){e.preventDefault();let a=active(),x={id:id||uid(),name:$('dName').value.trim(),phone:$('dPhone').value.trim(),total:num($('dTotal').value),paid:num($('dPaid').value),due:$('dDue').value,note:$('dNote').value.trim()};if(!x.name||!x.total)return;let old=a.debts.find(d=>d.id===id);old?Object.assign(old,x):a.debts.push(x);save();closeModal();toast('بدهی ذخیره شد')}
function addPayment(id){let d=active().debts.find(x=>x.id===id);if(!d)return;let v=prompt(`مبلغ پرداختی برای ${d.name} را وارد کنید:`,remaining(d));if(v!==null){let p=num(v);if(p>0){d.paid=Math.min(d.total,d.paid+p);save();toast('پرداخت ثبت شد')}}}
function deleteDebt(id){if(confirm('این بدهی حذف شود؟')){active().debts=active().debts.filter(x=>x.id!==id);save()}}
function renderDebts(){let a=active(),q=($('debtSearch')?.value||'').toLowerCase(),f=$('debtFilter')?.value||'',arr=a.debts.filter(d=>{let r=remaining(d),ov=r>0&&d.due&&d.due<today();return(!q||(`${d.name} ${d.phone}`).toLowerCase().includes(q))&&(!f||(f==='open'&&r>0)||(f==='paid'&&!r)||(f==='overdue'&&ov))}).sort((x,y)=>y.due.localeCompare(x.due));$('debtsList').innerHTML=arr.length?arr.map(d=>{let r=remaining(d),ov=r>0&&d.due<today(),pct=Math.min(100,d.paid/Math.max(1,d.total)*100);return `<div class="debt-card"><div class="debt-head"><strong>👤 ${esc(d.name)}</strong><b class="${r?'negative':'success'}">${money(r)}</b></div><div class="debt-meta"><span>📞 ${esc(d.phone||'بدون شماره')}</span><span>کل: ${money(d.total)}</span><span>پرداخت: ${money(d.paid)}</span><span class="${ov?'negative':''}">سررسید: ${formatDate(d.due)}</span></div><div class="progress"><i style="width:${pct}%"></i></div><div class="actions" style="margin-top:9px">${r?`<button onclick="addPayment('${d.id}')">💵 ثبت پرداخت</button>`:''}<button onclick="openDebt('${d.id}')">✏️ ویرایش</button><button onclick="deleteDebt('${d.id}')">🗑️ حذف</button></div></div>`}).join(''):'<div class="empty">بدهکاری ثبت نشده است.</div>'}
function loanPaid(l){return (l.payments||[]).reduce((s,p)=>s+num(p.amount),0)}
function loanRemaining(l){return Math.max(0,num(l.totalPayable)-loanPaid(l))}
function loanPaidCount(l){return (l.payments||[]).length}
function loanNextDate(l){let due=l.due;if(!due)return '';let [y,m,d]=due.split('-').map(Number);let n=loanPaidCount(l);let dt=new Date(y,m-1,d);dt.setMonth(dt.getMonth()+n);return `${dt.getFullYear()}-${pad2(dt.getMonth()+1)}-${pad2(dt.getDate())}`}
function loanBankOptions(selected){return BANKS.map(b=>`<option ${selected===b?'selected':''}>${b}</option>`).join('')}
function openLoan(id=''){let a=active(),x=a.loans.find(l=>l.id===id);openModal(x?'ویرایش وام / قسط':'ثبت وام بانکی',`<form class="form" onsubmit="saveLoan(event,'${id}')"><div class="row"><div><label>بانک</label><select id="lBank" class="bank-select">${loanBankOptions(x?.bank||'')}</select></div><div><label>عنوان وام / تسهیلات</label><input id="lTitle" required value="${esc(x?.title||'وام جدید')}"></div></div><div class="row"><div><label>مبلغ دریافتی وام</label><input id="lPrincipal" inputmode="numeric" value="${x?.principal||''}"></div><div><label>مجموع مبلغ قابل پرداخت</label><input id="lTotal" inputmode="numeric" required value="${x?.totalPayable||''}"></div></div><div class="row"><div><label>مبلغ هر قسط</label><input id="lInstallment" inputmode="numeric" required value="${x?.installment||''}"></div><div><label>تعداد کل اقساط</label><input id="lCount" inputmode="numeric" required value="${x?.count||''}"></div></div><div><label>تاریخ اولین سررسید</label>${dateField('lDue',x?.due||today())}</div><div><label>توضیحات</label><textarea id="lNote">${esc(x?.note||'')}</textarea></div>${x?'':'<label style="display:flex;align-items:center;gap:8px;color:var(--text)"><input id="lIncome" type="checkbox"> مبلغ دریافت وام به عنوان درآمد ثبت شود</label>'}<div class="row"><button class="primary">ذخیره</button><button type="button" class="secondary" onclick="closeModal()">انصراف</button></div></form>`)}
function saveLoan(e,id){e.preventDefault();try{let a=active(),old=a.loans.find(l=>l.id===id),x={id:id||uid(),bank:$('lBank').value,title:$('lTitle').value.trim(),principal:num($('lPrincipal').value),totalPayable:num($('lTotal').value),installment:num($('lInstallment').value),count:num($('lCount').value),due:readJalali('lDue'),note:$('lNote').value.trim(),payments:old?.payments||[]};if(!x.title||!x.totalPayable||!x.installment||!x.count)return;old?Object.assign(old,x):a.loans.push(x);if(!old&&$('lIncome')?.checked&&x.principal){a.transactions.push({id:uid(),type:'income',amount:x.principal,date:today(),note:`دریافت ${x.title} - ${x.bank}`,category:'وام بانکی'})}save();closeModal();toast('وام بانکی ذخیره شد')}catch(err){toast(err.message||'تاریخ را بررسی کنید')}}
function addLoanPayment(id){let a=active(),l=a.loans.find(x=>x.id===id);if(!l)return;openModal('ثبت پرداخت قسط',`<form class="form" onsubmit="saveLoanPayment(event,'${id}')"><div class="alert green">مانده این وام: <b>${money(loanRemaining(l))}</b></div><label>مبلغ پرداخت</label><input id="lpAmount" inputmode="numeric" required value="${Math.min(num(l.installment),loanRemaining(l))}"><label>تاریخ پرداخت</label>${dateField('lpDate',today())}<label>توضیحات</label><input id="lpNote" value="قسط ${loanPaidCount(l)+1} - ${l.title}"><button class="primary">ثبت پرداخت</button></form>`)}
function saveLoanPayment(e,id){e.preventDefault();try{let a=active(),l=a.loans.find(x=>x.id===id),amount=num($('lpAmount').value),date=readJalali('lpDate');if(!l||amount<=0||amount>loanRemaining(l))return;l.payments.push({id:uid(),amount,date,note:$('lpNote').value.trim()});a.transactions.push({id:uid(),type:'expense',amount,date,note:`🏦 ${l.bank} - ${l.title} - قسط ${loanPaidCount(l)}`,category:'قسط بانکی'});save();closeModal();toast('پرداخت قسط ثبت شد')}catch(err){toast(err.message||'تاریخ را بررسی کنید')}}
function deleteLoan(id){if(confirm('این وام و تاریخچه اقساط حذف شود؟')){active().loans=active().loans.filter(x=>x.id!==id);save();toast('وام حذف شد')}}
function renderLoans(){let a=active(),q=($('loanSearch')?.value||'').toLowerCase(),f=$('loanFilter')?.value||'',arr=(a.loans||[]).filter(l=>{let r=loanRemaining(l),done=r<=0,due=loanNextDate(l)||l.due,ov=r>0&&due<today();return(!q||(`${l.bank} ${l.title}`).toLowerCase().includes(q))&&(!f||(f==='open'&&r>0)||(f==='done'&&done)||(f==='overdue'&&ov))}).sort((x,y)=>(loanNextDate(x)||x.due).localeCompare(loanNextDate(y)||y.due));let rem=arr.reduce((s,l)=>s+loanRemaining(l),0),next=arr.filter(l=>loanRemaining(l)>0).sort((x,y)=>(loanNextDate(x)||x.due).localeCompare(loanNextDate(y)||y.due))[0];$('loansSummary').innerHTML=`<div class="stats" style="margin:0 0 12px"><div class="stat"><b>${money(rem)}</b><span>مانده کل وام‌ها</span></div><div class="stat"><b>${next?money(Math.min(num(next.installment),loanRemaining(next))):'—'}</b><span>قسط بعدی</span></div><div class="stat"><b>${next?formatDate(loanNextDate(next)||next.due):'—'}</b><span>سررسید بعدی</span></div></div>`;$('loansList').innerHTML=arr.length?arr.map(l=>{let rem=loanRemaining(l),cnt=loanPaidCount(l),pct=Math.min(100,loanPaid(l)/Math.max(1,num(l.totalPayable))*100),due=loanNextDate(l)||l.due,ov=rem>0&&due<today();return `<div class="loan-card"><div class="loan-top"><div><strong>🏦 ${esc(l.title)}</strong><div class="loan-bank">${esc(l.bank)}</div></div><b class="${rem?'negative':'success'}">${money(rem)}</b></div><div class="loan-meta"><span>قسط: ${money(l.installment)}</span><span>${fa(cnt)} از ${fa(l.count)} قسط</span><span class="${ov?'negative':''}">سررسید: ${formatDate(due)}</span></div><div class="progress"><i style="width:${pct}%"></i></div><div class="actions" style="margin-top:9px">${rem?`<button onclick="addLoanPayment('${l.id}')">💵 ثبت پرداخت قسط</button>`:''}<button onclick="loanHistory('${l.id}')">📋 历چه</button><button onclick="openLoan('${l.id}')">✏️ ویرایش</button><button onclick="deleteLoan('${l.id}')">🗑️ حذف</button></div></div>`}).join(''):'<div class="empty">هنوز وام یا قسط بانکی ثبت نشده است.</div>'}
function loanHistory(id){let l=active().loans.find(x=>x.id===id);if(!l)return;openModal('تاریخچه پرداخت اقساط',l.payments?.length?`<div class="list">${l.payments.map((p,i)=>`<div class="item"><div><b>قسط ${fa(i+1)}</b><small>${formatDate(p.date)}${p.note?' • '+esc(p.note):''}</small></div><strong>${money(p.amount)}</strong></div>`).join('')}</div>`:'<div class="empty">هنوز پرداختی ثبت نشده است.</div>')}

function openGoal(id=''){let x=active().goals.find(g=>g.id===id);openModal(x?'ویرایش هدف':'هدف پس‌انداز',`<form class="form" onsubmit="saveGoal(event,'${id}')"><label>نام هدف</label><input id="gName" required value="${esc(x?.name||'مثلاً خرید گوشی جدید')}"><label>مبلغ هدف</label><input id="gTarget" inputmode="numeric" required value="${x?.target||''}"><button class="primary">ذخیره هدف</button></form>`)}
function saveGoal(e,id){e.preventDefault();let a=active(),x={id:id||uid(),name:$('gName').value.trim(),target:num($('gTarget').value),saved:id?(a.goals.find(g=>g.id===id)?.saved||0):0,created:today()};let old=a.goals.find(g=>g.id===id);old?Object.assign(old,x):a.goals.push(x);save();closeModal();toast('هدف ذخیره شد')}
function deleteGoal(id){if(confirm('هدف حذف شود؟')){active().goals=active().goals.filter(x=>x.id!==id);save()}}
function goalHTML(arr){return arr.length?arr.map(g=>{let pct=Math.min(100,num(g.saved)/Math.max(1,num(g.target))*100);return `<div class="goal"><div class="goal-top"><strong>🎯 ${esc(g.name)}</strong><b>${fa(Math.round(pct))}٪</b></div><div class="nums">${money(g.saved)} از ${money(g.target)} • باقی‌مانده ${money(Math.max(0,num(g.target)-num(g.saved)))}</div><div class="progress"><i style="width:${pct}%"></i></div></div>`}).join(''):'<div class="empty">هدف پس‌اندازی ندارید.</div>'}
function renderSavings(){let a=active();$('goalsList').innerHTML=(a.goals||[]).length?a.goals.map(g=>goalHTML([g])+`<div class="actions" style="margin:-5px 0 9px"><button onclick="openGoal('${g.id}')">✏️ ویرایش</button><button onclick="deleteGoal('${g.id}')">🗑️ حذف</button></div>`).join(''):'<div class="empty">هنوز هدف ثبت نشده است.</div>';let total=a.savings.reduce((s,x)=>s+num(x.amount),0);$('savingSummary').innerHTML=`<div class="alert green">مجموع پس‌انداز: <b>${money(total)}</b></div>`;let arr=[...a.savings].sort((x,y)=>y.date.localeCompare(x.date));$('savingHistory').innerHTML=arr.length?arr.map(x=>`<div class="item"><div><b>💰 ${money(x.amount)}</b><small>${formatDate(x.date)}${x.note?' • '+esc(x.note):''}</small></div><button class="danger" onclick="deleteSaving('${x.id}')">حذف</button></div>`).join(''):'<div class="empty">هنوز پس‌اندازی ثبت نشده است.</div>'}
function openSaving(){let goals=active().goals;openModal('ثبت پس‌انداز',`<form class="form" onsubmit="saveSaving(event)"><label>مبلغ</label><input id="sAmount" inputmode="numeric" required><label>تاریخ</label>${dateField("sDate",today())}<label>هدف (اختیاری)</label><select id="sGoal"><option value="">بدون هدف</option>${goals.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('')}</select><label>توضیحات</label><input id="sNote"><button class="primary">ثبت پس‌انداز</button></form>`)}
function saveSaving(e){e.preventDefault();let a=active(),x={id:uid(),amount:num($('sAmount').value),date:readJalali('sDate'),note:$('sNote').value.trim(),goalId:$('sGoal').value};if(!x.amount)return;a.savings.push(x);if(x.goalId){let g=a.goals.find(g=>g.id===x.goalId);if(g)g.saved=num(g.saved)+x.amount}save();closeModal();toast('پس‌انداز ثبت شد')}
function deleteSaving(id){if(confirm('این پس‌انداز حذف شود؟')){let a=active(),x=a.savings.find(s=>s.id===id);if(x?.goalId){let g=a.goals.find(g=>g.id===x.goalId);if(g)g.saved=Math.max(0,num(g.saved)-num(x.amount))}a.savings=a.savings.filter(s=>s.id!==id);save()}}
function spentCat(cat,mo){return active().transactions.filter(x=>x.type==='expense'&&x.category===cat&&monthKey(x.date)===mo).reduce((s,x)=>s+num(x.amount),0)}
function budgetHTML(arr){return arr.length?arr.map(b=>{let used=spentCat(b.category,b.month),pct=Math.min(100,used/Math.max(1,num(b.limit))*100);return `<div class="goal"><div class="goal-top"><strong>📊 ${esc(b.category)}</strong><b>${fa(Math.round(pct))}٪</b></div><div class="nums">${money(used)} از ${money(b.limit)} • ${formatJMonth(b.month)}</div><div class="progress"><i style="width:${pct}%"></i></div></div>`}).join(''):'<div class="empty">بودجه‌ای برای این ماه ثبت نشده.</div>'}
function openBudget(id=''){let x=active().budgets.find(b=>b.id===id),mo=x?.month||currentJMonth();openModal(x?'ویرایش بودجه':'بودجه ماهانه',`<form class="form" onsubmit="saveBudget(event,'${id}')"><label>دسته‌بندی هزینه</label><select id="bCat">${DEFAULT_CATS.map(c=>`<option ${x?.category===c?'selected':''}>${c}</option>`).join('')}</select><div class="row"><div><label>سقف بودجه</label><input id="bLimit" inputmode="numeric" required value="${x?.limit||''}"></div><div><label>ماه بودجه (شمسی)</label><input id="bMonth" type="text" inputmode="numeric" required placeholder="۱۴۰۵/۰۷" value="${mo?formatJMonth(mo):''}"></div></div><button class="primary">ذخیره بودجه</button></form>`)}
function saveBudget(e,id){e.preventDefault();try{let a=active(),v=$('bMonth').value.replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/[-.]/g,'/'),p=v.split('/').map(Number);if(p.length!==2||p[0]<1300||p[1]<1||p[1]>12)throw new Error('ماه شمسی نامعتبر است');let g=j2g(p[0],p[1],1),x={id:id||uid(),category:$('bCat').value,limit:num($('bLimit').value),month:`${g[0]}-${pad2(g[1])}`},old=a.budgets.find(b=>b.id===id);old?Object.assign(old,x):a.budgets.push(x);save();closeModal();toast('بودجه ذخیره شد')}catch(err){toast(err.message||'ماه را بررسی کنید')}}
function deleteBudget(id){if(confirm('بودجه حذف شود؟')){active().budgets=active().budgets.filter(x=>x.id!==id);save()}}
function renderBudgets(){let a=active();$('budgetsList').innerHTML=a.budgets.length?a.budgets.slice().sort((x,y)=>y.month.localeCompare(x.month)).map(b=>budgetHTML([b])+`<div class="actions" style="margin:-4px 0 9px"><button onclick="openBudget('${b.id}')">✏️ ویرایش</button><button onclick="deleteBudget('${b.id}')">🗑️ حذف</button></div>`).join(''):'<div class="empty">هنوز بودجه‌ای ثبت نشده است.</div>'}
function toggleMoreNav(e){e?.stopPropagation();$('moreNav').classList.toggle('hidden');$('moreNavArrow').textContent=$('moreNav').classList.contains('hidden')?'⌄':'⌃'}
function closeMoreNav(){$('moreNav').classList.add('hidden');$('moreNavArrow').textContent='⌄'}
function openShopView(btn){switchAccount('shop');showView('dashboard',btn);document.querySelectorAll('#nav button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');setTimeout(drawMainChart,50)}
function showView(id,btn){closeMoreNav();document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));$(id).classList.remove('hidden');document.querySelectorAll('#nav button').forEach(b=>b.classList.remove('active'));let primary=['dashboard','transactions','reports'].includes(id);if(primary){document.querySelector(`#nav button[data-view=\"${id}\"]`)?.classList.add('active')}else{$('.more-nav-btn')?.classList.add('active')}if(id==='reports')renderReports();if(id==='dashboard')setTimeout(drawMainChart,50);if(id==='loans')renderLoans();if(id==='debts')renderDebts();if(id==='savings'){renderGoals();renderSavings()}if(id==='budgets')renderBudgets();scrollTo({top:0,behavior:'smooth'})}
function drawLine(canvas,series,labels){let ctx=canvas.getContext('2d'),w=canvas.clientWidth*devicePixelRatio,h=canvas.clientHeight*devicePixelRatio;canvas.width=w;canvas.height=h;ctx.clearRect(0,0,w,h);let vals=series.flatMap(s=>s.values),max=Math.max(1,...vals)*1.15;let pad={l:12*devicePixelRatio,r:10*devicePixelRatio,t:15*devicePixelRatio,b:30*devicePixelRatio},W=w-pad.l-pad.r,H=h-pad.t-pad.b;ctx.font=`${10*devicePixelRatio}px Tahoma`;labels.forEach((lab,i)=>{let x=pad.l+(W*(labels.length===1?0.5:i/(labels.length-1)));ctx.fillStyle=getComputedStyle(document.body).getPropertyValue('--muted');ctx.textAlign='center';ctx.fillText(lab,x,h-7*devicePixelRatio)});series.forEach(s=>{ctx.beginPath();s.values.forEach((v,i)=>{let x=pad.l+(W*(labels.length===1?0.5:i/(labels.length-1))),y=pad.t+H-(v/max)*H;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle=s.color;ctx.lineWidth=2.3*devicePixelRatio;ctx.stroke();s.values.forEach((v,i)=>{let x=pad.l+(W*(labels.length===1?0.5:i/(labels.length-1))),y=pad.t+H-(v/max)*H;ctx.beginPath();ctx.arc(x,y,3*devicePixelRatio,0,Math.PI*2);ctx.fillStyle=s.color;ctx.fill()})})}
function drawMainChart(){let a=active(),months=[];let d=new Date();d.setDate(1);for(let i=5;i>=0;i--){let x=new Date(d);x.setMonth(d.getMonth()-i);months.push(x.toISOString().slice(0,7))}let labels=months.map(m=>formatJMonth(m).replace(/^[^ ]+ /,'')),ser=['income','expense'].map((type,j)=>({color:j?'#dc2626':'#2563eb',values:months.map(m=>a.transactions.filter(x=>x.type===type&&monthKey(x.date)===m).reduce((s,x)=>s+num(x.amount),0))}));ser.push({color:'#16a34a',values:months.map(m=>a.savings.filter(x=>monthKey(x.date)===m).reduce((s,x)=>s+num(x.amount),0))});drawLine($('mainChart'),ser,labels)}
function setReport(m){reportMode=m;renderReports()}
function reportGroups(){let a=active(),tx=a.transactions||[],map=new Map();let key=x=>reportMode==='day'?x.date:reportMode==='year'?x.date.slice(0,4):x.date.slice(0,7);tx.forEach(x=>{let k=key(x);if(!map.has(k))map.set(k,{income:0,expense:0});map.get(k)[x.type]+=num(x.amount)});return [...map.entries()].sort((a,b)=>a[0].localeCompare(b[0])).slice(-12)}
function renderReports(){let g=reportGroups(),income=g.reduce((s,x)=>s+x[1].income,0),expense=g.reduce((s,x)=>s+x[1].expense,0),saving=active().savings.reduce((s,x)=>s+num(x.amount),0);$('reportSummary').innerHTML=`<div class="stats" style="margin:0 0 12px"><div class="stat"><b>${money(income)}</b><span>درآمد</span></div><div class="stat"><b>${money(expense)}</b><span>هزینه</span></div><div class="stat"><b>${money(saving)}</b><span>پس‌انداز</span></div><div class="stat"><b>${money(income-expense-saving)}</b><span>سود/مانده</span></div><div class="stat"><b>${money(totals().debt)}</b><span>طلب</span></div></div>`;drawLine($('reportChart'),[{color:'#2563eb',values:g.map(x=>x[1].income)},{color:'#dc2626',values:g.map(x=>x[1].expense)}],g.map(x=>x[0].length===10?isoToJalali(x[0]):(x[0].length===7?formatJMonth(x[0]):fa(x[0]))));$('reportTable').innerHTML=g.length?`<div class="table-wrap"><table class="table"><tr><th>دوره</th><th>درآمد</th><th>هزینه</th><th>خالص</th></tr>${g.map(x=>`<tr><td>${x[0].length===10?isoToJalali(x[0]):(x[0].length===7?formatJMonth(x[0]):fa(x[0]))}</td><td class="success">${money(x[1].income)}</td><td class="negative">${money(x[1].expense)}</td><td>${money(x[1].income-x[1].expense)}</td></tr>`).join('')}</table></div>`:'<div class="empty">داده‌ای برای گزارش نیست.</div>'}
function csvCell(v){return '"'+String(v??'').replace(/"/g,'""')+'"'}
function exportCSV(){let rows=[['حساب','نوع','مبلغ','تاریخ','دسته‌بندی','توضیحات']];Object.entries(data.accounts).forEach(([acc,a])=>(a.transactions||[]).forEach(x=>rows.push([acc,x.type,x.amount,x.date,x.category,x.note])));let csv='\uFEFF'+rows.map(r=>r.map(csvCell).join(',')).join('\n');download(csv,'financial-transactions.csv','text/csv;charset=utf-8')}
function exportJSON(){download(JSON.stringify(data,null,2),'financial-manager-backup.json','application/json')}
function exportAll(){let pack={exportedAt:new Date().toISOString(),app:'financial-manager-pro',data};download(JSON.stringify(pack,null,2),'financial-manager-complete-backup.json','application/json')}
function download(content,name,type){let b=new Blob([content],{type}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importJSON(){let i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=()=>{let r=new FileReader();r.onload=()=>{try{let p=JSON.parse(r.result),d=p.data||p;if(!d.accounts||!d.accounts.personal||!d.accounts.shop)throw 0;data=d;save();closeSettings();toast('پشتیبان با موفقیت وارد شد')}catch{alert('فایل پشتیبان معتبر این برنامه نیست.')}};r.readAsText(i.files[0])};i.click()}
function togglePrivacy(){privacy=!privacy;renderAll();toast(privacy?'مبالغ مخفی شد':'مبالغ نمایش داده شد')}
function toggleDark(){data.settings.dark=!data.settings.dark;document.body.classList.toggle('dark',data.settings.dark);localStorage.setItem(KEY,JSON.stringify(data));toast(data.settings.dark?'حالت تاریک فعال شد':'حالت روشن فعال شد')}
function openSettings(){ $('personalName').value=data.settings.personalName;$('shopName').value=data.settings.shopName;$('settingsModal').classList.remove('hidden')}
function closeSettings(){$('settingsModal').classList.add('hidden')}
function saveNames(){data.settings.personalName=$('personalName').value.trim()||'حساب شخصی';data.settings.shopName=$('shopName').value.trim()||'حساب مغازه تعمیرات موبایل';save();closeSettings();toast('نام حساب‌ها ذخیره شد')}
function saveRatesKey(){toast('نرخ دلار و طلا به‌صورت خودکار دریافت می‌شود')}
function formatRate(v){return fa(Math.round(Number(v)||0))}
function setPin(){let p=prompt('یک PIN چهار تا هشت رقمی وارد کنید:','');if(p===null)return;if(!/^\d{4,8}$/.test(p)){alert('PIN باید ۴ تا ۸ رقم باشد.');return}data.settings.pin=p;save();toast('PIN تنظیم شد')}
function lockApp(){if(!data.settings.pin){alert('ابتدا برای برنامه PIN تنظیم کنید.');return}$('unlockPin').value='';$('lockScreen').classList.remove('hidden');closeSettings()}
function unlock(){let p=$('unlockPin').value;if(p===data.settings.pin){$('lockScreen').classList.add('hidden');$('lockMsg').textContent=''}else $('lockMsg').textContent='PIN اشتباه است.'}
function toggleFab(){fabOpen=!fabOpen;$('fabMenu').classList.toggle('hidden',!fabOpen)}
function clearAll(){if(confirm('تمام اطلاعات هر دو حساب از این دستگاه حذف شود؟ این کار قابل برگشت نیست.')){localStorage.removeItem(KEY);location.reload()}}
function init(){
 document.body.classList.toggle('dark',!!data.settings.dark);
 if(data.settings.pin)$('lockScreen').classList.remove('hidden');
 renderAll();
 if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
}
init();
